site_name: Geometry
repo_url: https://github.com/ksell8/geometry
edit_uri: blob/main/geometry/doc/docs/
site_description: Making Geometry Fun!
site_author: Kurt Sell
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - What is Geometry?: guide/history.md
  - Lines: guide/lines.md
  - Angles: guide/angles.md
  - 2D Shapes:
    site_name: Geometry
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - What is Geometry?: guide/history.md
  - Lines: guide/lines.md
  - Angles: guide/angles.md
  - 2D Shapes: 
    - Transformations: guide/shapes/transformations.md
    - Triangles: guide/shapes/triangles.md
    - Quadrilaterals: guide/shapes/quadrilaterals.md
    - Circles: guide/shapes/circles.md

